version: '3'
services:
 
  mysql:
   container_name: some-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: dashboardisep
    MYSQL_ROOT_PASSWORD: root
   ports:
   - "3306:3306"
   restart: always
  
  app:
    restart: always
    build: ./back
    working_dir: /back
    volumes:
      - ./back:/back
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    ports:
    - "8080:8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql