version: '2'
services:
    mysql:
        image: mysql
        ports:
              - "3306:3306"
        volumes:
            - ./database:/tmp/database
        environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: dashboardisep

    dashboardisep:
        image: java:openjdk-8u91-jdk
        working_dir: /app
        volumes:
            - ./:/app
        command: java -jar back/target/dashboardisep-0.0.1-SNAPSHOT.jar
        depends_on:
            - mysql
        ports:
            - "80:8080"

